1. Write a NumPy program to print the NumPy version in your system.

In [3]:
import numpy as np

np.__version__

'1.24.1'

2. Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.

In [8]:
lst = [12.23, 13.32, 100, 36.32]
np.array(lst)

array([ 12.23,  13.32, 100.  ,  36.32])

3.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [9]:
np.arange(2, 11).reshape((3, 3))

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

4. Write a NumPy program to create a null vector of size 10 and update sixth value to 11

In [11]:
x = np.zeros(10)
x[5] = 11
x

array([ 0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.])

5. Write a NumPy program to create an array with values ranging from 12 to 38

In [13]:
np.arange(12, 38)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

6. Write a NumPy program to reverse an array (first element becomes last)

In [15]:
y = np.array([1, 2, 3, 4, 5])
y[::-1]

array([5, 4, 3, 2, 1])

7. Write a NumPy program to convert an array to a float type.

In [19]:
y = np.array([1, 2, 3, 4, 5], dtype=float)
print(y)
z = np.array([6, 7, 8, 9])
np.asfarray(z)

[1. 2. 3. 4. 5.]


array([6., 7., 8., 9.])

8. Write a NumPy program to create a 2d array with 1 on the border and 0 inside

In [47]:
a = np.ones((6, 6))
a[1:-1, 1:-1] = 0
a


array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

9. Write a NumPy program to add a border (filled with 0's) around an existing array.

In [60]:
a1 = np.arange(1, 26).reshape(5, 5)
a2 = np.pad(array=a1, pad_width=1, mode='constant', constant_values=0)
a2

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  0],
       [ 0,  6,  7,  8,  9, 10,  0],
       [ 0, 11, 12, 13, 14, 15,  0],
       [ 0, 16, 17, 18, 19, 20,  0],
       [ 0, 21, 22, 23, 24, 25,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

10. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [62]:
arr = np.ones((8, 8), dtype=int)
arr[0::2, 1::2] = 0
arr[1::2, 0::2] = 0
arr

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])