1. Write a NumPy program to print the NumPy version in your system.

In [1]:
import numpy as np

np.__version__

'1.24.1'

2. Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.

In [2]:
lst = [12.23, 13.32, 100, 36.32]
np.array(lst)

array([ 12.23,  13.32, 100.  ,  36.32])

3.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [3]:
np.arange(2, 11).reshape((3, 3))

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

4. Write a NumPy program to create a null vector of size 10 and update sixth value to 11

In [4]:
x = np.zeros(10)
x[5] = 11
x

array([ 0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.])

5. Write a NumPy program to create an array with values ranging from 12 to 38

In [5]:
np.arange(12, 38)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

6. Write a NumPy program to reverse an array (first element becomes last)

In [6]:
y = np.array([1, 2, 3, 4, 5])
y[::-1]

array([5, 4, 3, 2, 1])

7. Write a NumPy program to convert an array to a float type.

In [7]:
y = np.array([1, 2, 3, 4, 5], dtype=float)
print(y)
z = np.array([6, 7, 8, 9])
np.asfarray(z)

[1. 2. 3. 4. 5.]


array([6., 7., 8., 9.])

8. Write a NumPy program to create a 2d array with 1 on the border and 0 inside

In [8]:
a = np.ones((6, 6))
a[1:-1, 1:-1] = 0
a


array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

9. Write a NumPy program to add a border (filled with 0's) around an existing array.

In [9]:
a1 = np.arange(1, 26).reshape(5, 5)
a2 = np.pad(array=a1, pad_width=1, mode='constant', constant_values=0)
a2

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  0],
       [ 0,  6,  7,  8,  9, 10,  0],
       [ 0, 11, 12, 13, 14, 15,  0],
       [ 0, 16, 17, 18, 19, 20,  0],
       [ 0, 21, 22, 23, 24, 25,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

10. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [10]:
arr = np.ones((8, 8), dtype=int)
arr[0::2, 1::2] = 0
arr[1::2, 0::2] = 0
arr

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

11. Write a NumPy program to convert a list and tuple into arrays

In [11]:
lst = [1, 2, 3, 4, 5]
tup = ((5, 6, 7, 8, 9),(1, 1, 1, 1, 1))

print(np.array(lst))
print(np.array(tup))

[1 2 3 4 5]
[[5 6 7 8 9]
 [1 1 1 1 1]]


12. Write a NumPy program to append values to the end of an array.

In [12]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 1, 1, 1])
np.append(a, b)

array([1, 2, 3, 4, 1, 1, 1, 1])

13. Write a NumPy program to create an empty and a full array.

In [13]:
print(np.empty((3, 5)))
print(np.full((3, 4), 5))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


14. Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees and vice versa. Values are stored into a NumPy array.

In [14]:
fvalues = [0, 12, 45.21, 34, 99.91, 32]
F = np.array(fvalues)
print("Values in Fahrenheit degrees:")
print(F)
print("Values in  Centigrade degrees:")
print(np.round((5 * F / 9 - 5 * 32 / 9), 2))

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91 32.  ]
Values in  Centigrade degrees:
[-17.78 -11.11   7.34   1.11  37.73   0.  ]


In [15]:
cvalues = [-17.78, -11.11, 7.34, 1.11, 37.73, 0]
C = np.array(cvalues)
print("Values in Centigrade degrees:")
print(C)
print("Values in  Fahrenheit degrees:")
print(np.round((9  * C / 5 + 32), 2))

Values in Centigrade degrees:
[-17.78 -11.11   7.34   1.11  37.73   0.  ]
Values in  Fahrenheit degrees:
[-0.   12.   45.21 34.   99.91 32.  ]


15. Write a NumPy program to find the real and imaginary parts of an array of complex numbers.

In [16]:
a = np.array([ 1.00000000 + 0.j,  0.70710678 + 0.70710678j])
print('Real part of the array')
r = np.real(a)
print(r)
print('Imaginary part of the array')
i = np.imag(a)
print(i)

Real part of the array
[1.         0.70710678]
Imaginary part of the array
[0.         0.70710678]


In [17]:
a.real

array([1.        , 0.70710678])

In [18]:
a.imag

array([0.        , 0.70710678])

16. Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.

In [19]:
a = np.ones((3, 3))
print('The number of elements, is: ', a.size)
print('The lenght of one array element in bytes is: ', a.itemsize)
print('The total bytes consumed by the elements is: ', a.nbytes)

The number of elements, is:  9
The lenght of one array element in bytes is:  8
The total bytes consumed by the elements is:  72


17. Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

In [20]:
a = np.arange(10, dtype=float)
print(a)
b = np.ones(10)
print(b)
np.in1d(a, b)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


array([False,  True, False, False, False, False, False, False, False,
       False])

18. Write a NumPy program to find common values between two arrays.

In [21]:
arr1 = np.array([0, 10, 20, 40, 60])
arr2 = np.array([10, 30, 40])
np.intersect1d(arr1, arr2)

array([10, 40])

19. Write a NumPy program to get the unique elements of an array.

In [22]:
a = np.array([10, 10, 20, 20, 30, 30])
np.unique(a)

array([10, 20, 30])

In [23]:
a = np.array([[1, 1, 3], [3, 3, 4]])
np.unique(a)

array([1, 3, 4])

20. Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2

In [24]:
a1 = np.array([0, 10, 20, 40, 60, 80])
a2 = np.array([10, 30, 40, 50, 70, 90])
print(a1)
print(a2)
print(np.setdiff1d(a1, a2))

[ 0 10 20 40 60 80]
[10 30 40 50 70 90]
[ 0 20 60 80]


21. Write a NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays.

In [25]:
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = np.array([10, 30, 40, 50, 70])
print("Array2: ",array2)
print("Unique values that are in only one (not both) of the input arrays:")
print(np.setxor1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10 30 40 50 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


22. Write a NumPy program to find the union of two arrays. Union will return the unique, sorted array of values that are in either of the two input arrays.

In [26]:
np.union1d(array1, array2)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80])

23. Write a NumPy program to test whether all elements in an array evaluate to True.

In [27]:
np.alltrue(array2)

True

24. Write a NumPy program to test whether any array element along a given axis evaluates to True.

In [28]:
a = np.arange(12).reshape((3, 4))
print(a)
b = a.any(axis=0)
print(b)
c = a.any(axis=1)
print(c)
np.any(array2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ True  True  True  True]
[ True  True  True]


True

25. Write a NumPy program to construct an array by repeating.

In [29]:
a = np.array([1, 2, 3, 4])
np.tile(a, 3)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

26. Write a NumPy program to repeat elements of an array.

In [30]:
np.repeat(a, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

27. Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array.

In [31]:
x = np.array([4, 2, 3, 3, 7, 8, 90, 2, 10]).reshape((3, 3))
print('Max index is: ', np.argmax(x))
print('Min index is: ', np.argmin(x))


Max index is:  6
Min index is:  1


28. Write a NumPy program compare two given arrays.

In [32]:
x = np.array([1, 2, 3])
y = np.array([2, 3, 3])

print(np.greater(x, y))
print(np.less(x, y))
print(np.equal(x, y))
print(np.less_equal(x, y))
print(np.greater_equal(x, y))
print(np.not_equal(x, y))

[False False False]
[ True  True False]
[False False  True]
[ True  True  True]
[False False  True]
[ True  True False]


29. Write a NumPy program to sort an along the first, last axis of an array.

In [33]:
a = np.array([[2,5],[6,4]])
print(a)
print('-' * 10)
print(np.sort(a, axis=0))
print('-' * 10)
print(np.sort(a, axis=1))

[[2 5]
 [6 4]]
----------
[[2 4]
 [6 5]]
----------
[[2 5]
 [4 6]]


30. Write a NumPy program to sort pairs of first name and last name return their indices. (first by last name, then by first name).

In [34]:
first_names = ('Betsey', 'Shelley', 'Lanell', 'Genesis', 'Margery')
last_names = ('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')
np.lexsort((first_names, last_names))

array([1, 3, 2, 4, 0], dtype=int64)

31. Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.

In [35]:
a = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(a)
print("Values bigger than 10 =", a[a>10])
print("Their indices are ", np.nonzero(a > 10))

Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


32. Write a NumPy program to save a NumPy array to a text file.

In [36]:
arr3 = np.array([[0, 10, 20], [20, 30, 40]])
np.savetxt('save.txt', arr3, delimiter=',')

33. Write a NumPy program to find the memory size of a NumPy array.

In [37]:
print("%d bytes" % (arr3.size * arr3.itemsize))

24 bytes


34. Write a NumPy program to create an array of ones and an array of zeros.

In [38]:
a = np.ones(2, dtype=float)
print(a)
b = np.ones(2, dtype=int)
print(b)
c = np.zeros(2, dtype=float)
print(c)
d = np.zeros(2, dtype=int)
print(d)

[1. 1.]
[1 1]
[0. 0.]
[0 0]


35. Write a NumPy program to change the dimension of an array.

In [39]:
a = np.arange(9)
print(a)
a.reshape((3, 3))

[0 1 2 3 4 5 6 7 8]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

36. Write a NumPy program to create a contiguous flattened array.

In [40]:
n = np.array([[10, 20, 30], [20, 40, 50]])
print(n)
n.ravel()


[[10 20 30]
 [20 40 50]]


array([10, 20, 30, 20, 40, 50])

37. Write a NumPy program to create a 2-dimensional array of size 2 x 3 (composed of 4-byte integer elements), also print the shape, type and data type of the array.

In [41]:
x = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
print(type(x))	
print(x.shape)
print(x.dtype)

<class 'numpy.ndarray'>
(2, 3)
int32


38. Write a NumPy program to create a new shape to an array without changing its data.

In [42]:
x = np.arange(6)
print(x)
print(x.reshape((2, 3)))
print(x.reshape((3, 2)))

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


39. Write a NumPy program to change the data type of an array.

In [43]:
x = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
print(x)
print("Data type of the array x is:",x.dtype)
# Change the data type of x
y = x.astype(float)
print("New Type: ",y.dtype)
print(y)

[[ 2  4  6]
 [ 6  8 10]]
Data type of the array x is: int32
New Type:  float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


40. Write a NumPy program to create a new array of 3*5, filled with 2

In [44]:
print(np.ones((3, 5)) * 2)
print('-' * 10)
print(np.full((3, 5), 2))

[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
----------
[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


41. Write a NumPy program to create an array of 10's with the same shape and type of a given array.

In [45]:
x = np.arange(4, dtype=np.int64)
y = np.full_like(x, 10)
y

array([10, 10, 10, 10], dtype=int64)

42. Write a NumPy program to create a 2-D array with ones on a diagonal and zeros elsewhere.

In [46]:
np.eye(9)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

43. Write a NumPy program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere

In [47]:
print(np.identity(4) * np.array([4, 5, 6, 8]))
print(np.diagflat([4, 5 ,6 ,8]))

[[4. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 6. 0.]
 [0. 0. 0. 8.]]
[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]


44. Write a NumPy program to create a 1-D array going from 0 to 50 and an array from 10 to 50

In [48]:
print(np.arange(50))
print(np.arange(10, 50))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


45. Write a NumPy program to Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive

In [49]:
np.linspace(start=2.5, stop=6.5, num=30)

array([2.5       , 2.63793103, 2.77586207, 2.9137931 , 3.05172414,
       3.18965517, 3.32758621, 3.46551724, 3.60344828, 3.74137931,
       3.87931034, 4.01724138, 4.15517241, 4.29310345, 4.43103448,
       4.56896552, 4.70689655, 4.84482759, 4.98275862, 5.12068966,
       5.25862069, 5.39655172, 5.53448276, 5.67241379, 5.81034483,
       5.94827586, 6.0862069 , 6.22413793, 6.36206897, 6.5       ])

46. Write a NumPy program to create a 1-D array of 20 element spaced evenly on a log scale between 2. and 5., exclusive.

In [50]:
np.logspace(start=2, stop=5, num=20, endpoint=False)

array([  100.        ,   141.25375446,   199.5262315 ,   281.83829313,
         398.10717055,   562.34132519,   794.32823472,  1122.0184543 ,
        1584.89319246,  2238.72113857,  3162.27766017,  4466.83592151,
        6309.5734448 ,  8912.50938134, 12589.25411794, 17782.79410039,
       25118.8643151 , 35481.33892336, 50118.72336273, 70794.57843841])

47. Write a NumPy program to create an array which looks like below array. Expected Output:
[[ 0. 0. 0.]
...........
[1. 1. 0.]
[ 1. 1. 1.]]

In [51]:
np.tri(N=4, M=3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

48. Write a NumPy program to create an array which looks like below array. Go to the editor
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 0 9 10]
[ 0 0 13]]

In [52]:
np.triu(np.arange(2, 14).reshape(4, 3), -1)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 0,  9, 10],
       [ 0,  0, 13]])

49. Write a NumPy program to collapse a 3-D array into one dimension array.

In [53]:
x = np.eye(3)
print(x)
y = x.flatten()
z = np.ravel(x, order='F')
print(y)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1. 0. 0. 0. 1. 0. 0. 0. 1.]
[1. 0. 0. 0. 1. 0. 0. 0. 1.]


50. Write a NumPy program to find the 4th element of a specified array.

In [54]:
x = np.array([[2, 4, 6], [6, 8, 10]])
print(x)
y = x.flatten()
print(y[3])

[[ 2  4  6]
 [ 6  8 10]]
6


In [55]:
x.flat[3]

6

51. Write a NumPy program to interchange two axes of an array

In [56]:
x = np.arange(9).reshape((3, 3))
print(x)
print(x.swapaxes(0, 1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


52. Write a NumPy program to move axes of an array to new positions. Other axes remain in their original order.

In [57]:
x = np.zeros((2, 3, 4))
print(x)
print(np.moveaxis(x, 0, -1).shape)
print(np.moveaxis(x, -1, 0).shape)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
(3, 4, 2)
(4, 2, 3)


53. Write a NumPy program to move the specified axis backwards, until it lies in a given position.

In [58]:
x = np.ones((2, 3, 4, 5))
np.rollaxis(x, 3, 1).shape # moves the the axe with index 3 on the index 1 axe

(2, 5, 3, 4)

54. Write a NumPy program to convert specified inputs to arrays with at least one dimension

In [59]:
x = 12.0
print(np.atleast_1d(x))
x = np.arange(6.0).reshape((2, 3))
print(np.atleast_1d(x))
print(np.atleast_1d(1, [3, 4]))

[12.]
[[0. 1. 2.]
 [3. 4. 5.]]
[array([1]), array([3, 4])]


55. Write a NumPy program to view inputs as arrays with at least two dimensions, three dimensions.

In [60]:
a = 3.0
print(np.atleast_2d(a))
a = np.arange(6.0).reshape((2, 3))
print(np.atleast_2d(a))
print(np.atleast_3d(a))

[[3.]]
[[0. 1. 2.]
 [3. 4. 5.]]
[[[0.]
  [1.]
  [2.]]

 [[3.]
  [4.]
  [5.]]]


56. Write a NumPy program to insert a new axis within a 2-D array.

In [61]:
x = np.arange(12).reshape((3, 4))
print(x)
print(x.shape)
y = np.expand_dims(x, axis=1)
print(y)
print(y.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
[[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]
(3, 1, 4)


57. Write a NumPy program to remove single-dimensional entries from a specified shape

In [62]:
x = np.ones((3, 1, 4, 1 ,1))
print(x.shape)
y = np.squeeze(x)
print(y.shape)

(3, 1, 4, 1, 1)
(3, 4)


58. Write a NumPy program to concatenate two 2-dimensional arrays

In [63]:
a = np.array([[0, 1, 3], [5, 7, 9]])
b = np.array([[0, 2, 4], [6, 8, 10]])
c = np.concatenate((a, b), axis=1)
d = np.concatenate((a, b), axis=0)
e = np.concatenate((a, b))
print(c)
print(d)
print(e)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]
[[ 0  1  3]
 [ 5  7  9]
 [ 0  2  4]
 [ 6  8 10]]
[[ 0  1  3]
 [ 5  7  9]
 [ 0  2  4]
 [ 6  8 10]]


59. Write a NumPy program to convert 1-D arrays as columns into a 2-D array

In [64]:
a = np.array((10,20,30))
b = np.array((40,50,60))
c = np.column_stack((a, b))
print(c)

[[10 40]
 [20 50]
 [30 60]]


60. Write a NumPy program to convert (in sequence depth wise (along third axis)) two 1-D arrays into a 2-D array.

In [65]:
a = np.array(([10], [20], [30]))
b = np.array(([40], [50], [60]))
c = np.dstack((a, b))
c

array([[[10, 40]],

       [[20, 50]],

       [[30, 60]]])

61. Write a NumPy program to split an array of 14 elements into 3 arrays, each of which has 2, 4, and 8 elements in the original order

In [66]:
a = np.arange(1, 15)
np.split(a, [2, 6])

[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]

62. Write a NumPy program to split of an array of shape 4x4 it into two arrays along the second axis

In [67]:
a = np.arange(16).reshape((4, 4))
np.hsplit(a, [2, 6])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]),
 array([], shape=(4, 0), dtype=int32)]

63. Write a NumPy program to get the number of nonzero elements in an array

In [68]:
a = np.array([[0, 10, 20], [20, 30, 40]])
np.count_nonzero(a)

5

64. Write a NumPy program to create a 5x5 matrix with row values ranging from 0 to 4

In [69]:
a = np.zeros((5, 5))
a += np.arange(5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

65. Write a NumPy program to test whether specified values are present in an array

In [70]:
a = np.array([[1.12,  2., 3.45], [2.33, 5.12, 6.]])
print(a)
print(2 in a)
print(0 in a)
print(2.3 in a)
print(6 in a)

[[1.12 2.   3.45]
 [2.33 5.12 6.  ]]
True
False
False
True


66. Write a NumPy program to create a vector of size 10 with values ranging from 0 to 1, both excluded

In [71]:
a = np.random.random(10)
print(a)
b = np.linspace(0, 1, num=10, endpoint=False)
b

[0.95291184 0.97492315 0.37077168 0.60886884 0.11052082 0.82276449
 0.14056741 0.47205482 0.10697195 0.75233585]


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

67. Write a NumPy program to make an array immutable (read-only)

In [72]:
x = np.zeros(10)
x.flags.writeable = False
x[0] = 1
x

ValueError: assignment destination is read-only

68. Write a NumPy program (using NumPy) to sum of all the multiples of 3 or 5 below 100

In [ ]:
x = np.arange(1, 100)
n = x[(x % 3 == 0) | (x % 5 == 0)]
print(n[:100])
n.sum()

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]


2318

69. Write a NumPy program to create an array with 10^3 elements

In [ ]:
np.arange(1e3)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100., 101., 102., 103., 104., 105., 106., 107., 108., 109.,
       110., 111., 112., 113., 114., 115., 116., 117., 118., 119., 120.,
       121., 122., 123., 124., 125., 126., 127., 128., 129., 130., 131.,
       132., 133., 134., 135., 136., 137., 138., 139., 140., 141., 142.,
       143., 144., 145., 146., 147., 148., 149., 15

70. Write a NumPy program to create display every element of a NumPy array

In [ ]:
x = np.arange(12)
for i in np.nditer(x):
    print(i, end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 

71. Write a NumPy program to create and display every element of a NumPy array in Fortran order

In [ ]:
x = np.arange(12).reshape(3, 4)
print("Aray: ", x)
print("Elements of the array in Fortan array:")
for x in np.nditer(x, order="F"):
    print(x, end=' ')

Aray:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Elements of the array in Fortan array:
0 4 8 1 5 9 2 6 10 3 7 11 

72. Write a NumPy program to create a 5x5x5 cube of 1's

In [ ]:
np.ones((5, 5, 5)).astype(int)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

73. Write a NumPy program to create an array of (3, 4) shape, multiply every element value by 3 and display the new array.

In [ ]:
a = np.arange(12).reshape((3, 4))
print(a)
print('-' * 20)
b = np.multiply(a, 3) # b = a * 3
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


74. Write a NumPy program to combine a one and a two dimensional array together and display their elements

In [ ]:
x = np.array([0, 1, 2, 3])
print(x)
print('-' * 20)
y = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
print(y)
print('-' * 20)

for i, j in np.nditer([x, y]):
    print("%d:%d" % (i, j))


[0 1 2 3]
--------------------
[[0 1 2 3]
 [4 5 6 7]]
--------------------
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


75. Write a NumPy program to create an array of zeros and three column types (integer, float, character)

In [ ]:
x = np.zeros((3), dtype=('i4, f4, a40'))
x

array([(0, 0., b''), (0, 0., b''), (0, 0., b'')],
      dtype=[('f0', '<i4'), ('f1', '<f4'), ('f2', 'S40')])

76. Write a NumPy program to create a function cube which cubes all the elements of an array.

In [ ]:
x = np.arange(10).reshape((5, 2))
print(x)

def cube_array(e):
    it = np.nditer([e, None])
    for a, b in it:
        b[...] = a*a*a
    return it.operands[1]

print(cube_array(x))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[  0   1]
 [  8  27]
 [ 64 125]
 [216 343]
 [512 729]]


77. Write a NumPy program to create an array of (3, 4) shape and convert the array elements in smaller chunks.

In [ ]:
x= np.arange(12).reshape(3, 4)
print("Original array elements:")
print(x)
print("Above array in small chuncks:")
for a in np.nditer(x, flags=['external_loop'], order='F'):
    print(a)

Original array elements:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Above array in small chuncks:
[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


78. Write a NumPy program to create a record array from a (flat) list of arrays

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array(['Red', 'Green', 'White', 'Orange'])
c = np.array([12.20, 15, 20, 40])

result = np.core.records.fromarrays([a, b, c], names='a, b, c')
result

rec.array([(1, 'Red', 12.2), (2, 'Green', 15. ), (3, 'White', 20. ),
           (4, 'Orange', 40. )],
          dtype=[('a', '<i4'), ('b', '<U6'), ('c', '<f8')])

79. Write a NumPy program to generate a generic 2D Gaussian-like array.

In [ ]:
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(x * x + y * y)
sigma, mu = 1.0, 0.0
g = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
print("2D Gaussian-like array:")
print(g)

2D Gaussian-like array:
[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0

80. Write a NumPy program to convert a NumPy array into Python list structure.

In [ ]:
a = np.arange(12).reshape((3, 4))
print(a.tolist())

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


81. Write a NumPy program to access an array by column

In [ ]:
a = np.arange(6).reshape((3, 2))
print(a)
print(a[:, 0])
print(a[:, 1])

[[0 1]
 [2 3]
 [4 5]]
[0 2 4]
[1 3 5]


82. Write a NumPy program to convert a NumPy array of float values to a NumPy array of integer values.

In [ ]:
a = np.array([1.9, 2., 3.69, 4.5])
print(a)
b = np.array(a, dtype=int)
print(b)
print(a.astype(int))

[1.9  2.   3.69 4.5 ]
[1 2 3 4]
[1 2 3 4]


83. Write a NumPy program to display NumPy array elements of floating values with given precision.

In [ ]:
x=np.array([ 0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349,             
0.35399976, 0.99469633, 0.0694458, 0.54711478])
np.set_printoptions(precision=3)
print(x)

[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


84. Write a NumPy program to suppresses the use of scientific notation for small numbers in NumPy array

In [ ]:
x = np.array([1.6e-10, 1.6, 1200, .235])
print(x)
np.set_printoptions(suppress=3)
x

[   0.       1.6   1200.       0.235]


array([   0.   ,    1.6  , 1200.   ,    0.235])

85. Write a NumPy program to create a NumPy array of 10 integers from a generator

In [ ]:
gen = (x for x in range(10))
np.fromiter(gen, np.int32)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

86. Write a NumPy program to add an extra column to a NumPy array.

In [ ]:
x = np.array([[10,20,30], [40,50,60]])
y = np.array([[100], [200]])

print(np.append(x, y, axis=1))

[[ 10  20  30 100]
 [ 40  50  60 200]]


87. Write a NumPy program to find unique rows in a NumPy array.

In [ ]:
x = np.array([[20, 20, 20, 0],
              [0, 20, 20, 20],
              [0, 20, 20, 20],
              [20, 20, 20, 0],
              [10, 20, 20,20]])
print(x)

np.unique(x, axis=0)

[[20 20 20  0]
 [ 0 20 20 20]
 [ 0 20 20 20]
 [20 20 20  0]
 [10 20 20 20]]


array([[ 0, 20, 20, 20],
       [10, 20, 20, 20],
       [20, 20, 20,  0]])

In [ ]:
y = np.ascontiguousarray(x).view(np.dtype((np.void, x.dtype.itemsize * x.shape[1])))
_, idx = np.unique(y, return_index=True)

unique_result = x[idx]
print("Unique rows of the above array:")
print(unique_result)

Unique rows of the above array:
[[ 0 20 20 20]
 [10 20 20 20]
 [20 20 20  0]]


88. Write a NumPy program to replace all elements of NumPy array that are greater than specified array.

In [ ]:
x = np.array([[ 0.42436315, 0.48558583, 0.32924763], [ 0.7439979,0.58220701,0.38213418], [ 0.5097581,0.34528799,0.1563123 ]])
print("Original array:")
print(x)
print("Replace all elements of the said array with .5 which are greater than .5")
x[x > .5] = .5
print(x)

Original array:
[[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


89. Write a NumPy program to remove specific elements in a NumPy array.

In [ ]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(a)
print('Prints the array without the 2nd, 4th and 5th elements')
np.delete(a, [1, 3, 4])

[ 10  20  30  40  50  60  70  80  90 100]
Prints the array without the 2nd, 4th and 5th elements


array([ 10,  30,  60,  70,  80,  90, 100])

90. Write a NumPy program to replace the negative values in a NumPy array with 0.

In [ ]:
x = np.array([-1, -4, 0, 2, 3, 4, 5, -6])
print(x)
x[x < 0] = 0
print(x)

[-1 -4  0  2  3  4  5 -6]
[0 0 0 2 3 4 5 0]


91. Write a NumPy program to remove all rows in a NumPy array that contain non-numeric values.

In [ ]:
x = np.array([[1,2,3], [4,5,np.nan], [7,8,9], [True, False, True]])
print(x)
print('-' * 20)
print(x[~np.isnan(x).any(axis=1)])

[[ 1.  2.  3.]
 [ 4.  5. nan]
 [ 7.  8.  9.]
 [ 1.  0.  1.]]
--------------------
[[1. 2. 3.]
 [7. 8. 9.]
 [1. 0. 1.]]


92. Write a NumPy program to select indices satisfying multiple conditions in a NumPy array

In [ ]:
a = np.array([97, 101, 105, 111, 117])
b = np.array(['a','e','i','o','u'])

print("Elements from the second array  corresponding to elements in the first array  that are greater than 100 and less than 110:")

print(b[(100 < a) & (a < 110)])

Elements from the second array  corresponding to elements in the first array  that are greater than 100 and less than 110:
['e' 'i']


93. Write a NumPy program to get the magnitude of a vector in NumPy.

In [ ]:
x = np.array([1,2,3,4,5])
print("Original array:")
print(x)
print("Magnitude of the vector:")
print(np.linalg.norm(x))

Original array:
[1 2 3 4 5]
Magnitude of the vector:
7.416198487095663


94. Write a NumPy program to count the frequency of unique values in NumPy array.

In [ ]:
a = np.array( [10, 10, 20, 10, 20, 20, 20, 30, 30, 50, 40, 40] )
print("Original array:")
print(a)
unique_elements, counts_elements = np.unique(a, return_counts=True)
print("Frequency of unique values of the said array:")
print(np.asarray((unique_elements, counts_elements)))

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


95. Write a NumPy program to check whether the NumPy array is empty or not.

In [ ]:
x = np.array([2, 2])
y = np.array([])
print(x.size)
print(y.size)

2
0


96. Write a NumPy program to divide each row by a vector element.

In [ ]:
x = np.array([[20, 20, 20], [30, 30, 30],[40, 40, 40]])
print("Original array:")
print(x)
v = np.array([20, 30, 40])
print("Vector:")
print(v)
print('-' * 20)
print(x / v[: ,None])
print('-' * 20)
print(x / v[None ,:])
print('-' * 20)
print(x / v)


Original array:
[[20 20 20]
 [30 30 30]
 [40 40 40]]
Vector:
[20 30 40]
--------------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
--------------------
[[1.           0.6666666667 0.5         ]
 [1.5          1.           0.75        ]
 [2.           1.3333333333 1.          ]]
--------------------
[[1.           0.6666666667 0.5         ]
 [1.5          1.           0.75        ]
 [2.           1.3333333333 1.          ]]


97. Write a NumPy program to print all the values of an array.

In [ ]:
a = np.arange(9).reshape((3, 3))
print(a)
for i in np.nditer(a):
    print(i, end=' ')

[[0 1 2]
 [3 4 5]
 [6 7 8]]
0 1 2 3 4 5 6 7 8 

98. Write a NumPy program to convert the raw data in an array to a binary string and then create an array.

In [ ]:
x = np.array([10, 20, 30], float)
print("Original array:")
print(x)
s = x.tobytes()
print("Binary string array:")
print(s)
print("Array using fromstring():")
y = np.frombuffer(s)
print(y)

Original array:
[10. 20. 30.]
Binary string array:
b'\x00\x00\x00\x00\x00\x00$@\x00\x00\x00\x00\x00\x004@\x00\x00\x00\x00\x00\x00>@'
Array using fromstring():
[10. 20. 30.]


99. Write a NumPy program to sum and compute the product of a NumPy array elements

In [ ]:
a = np.array([10, 20 ,30])
b = np.sum(a)
print('Sum is: ', b)
c = np.prod(a)
print('Product is: ', c)

Sum is:  60
Product is:  6000


100. Write a NumPy program to take values from a source array and put them at specified indices of another array.

In [ ]:
x = np.array([10, 10, 20, 10, 30, 10])
print(x)
print('Put 10 in 3rd and 5th possition of the above array')
y = np.array([10, 10, 20, 0])
x.put([2, 4], y)
print(x)

[10 10 20 10 30 10]
Put 10 in 3rd and 5th possition of the above array
[10 10 10 10 10 10]
