1. Write a NumPy program to generate five random numbers from the normal distribution.

In [2]:
import numpy as np

np.random.normal(size=5)

array([ 1.28897247,  0.13689311, -0.28165663, -0.47436691,  0.40706638])

2. Write a NumPy program to generate six random integers between 10 and 30.

In [4]:
np.random.randint(10, 30, size=6)

array([10, 21, 10, 28, 16, 26])

3. Write a NumPy program to create a 3x3x3 array with random values.

In [5]:
np.random.random((3, 3, 3))

array([[[0.56398659, 0.17726924, 0.90890654],
        [0.56701943, 0.34860355, 0.2856566 ],
        [0.65862667, 0.54149   , 0.41853776]],

       [[0.45709585, 0.49140038, 0.0821381 ],
        [0.27711911, 0.63021305, 0.7608674 ],
        [0.80046214, 0.04870176, 0.8252365 ]],

       [[0.55704569, 0.0206119 , 0.99576229],
        [0.55769368, 0.14557293, 0.21323862],
        [0.54366379, 0.18405173, 0.80344716]]])

4. Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

In [6]:
x = np.random.random((5, 5))
print(x)

print('Minumum: ', np.min(x))
print('Maximum: ', np.max(x))

[[0.53423179 0.56842573 0.5780583  0.82606596 0.58768516]
 [0.84087247 0.65677722 0.28557253 0.04764386 0.55720079]
 [0.15213604 0.17947947 0.58816275 0.45876752 0.12144738]
 [0.91662908 0.82752116 0.54906852 0.14547384 0.24610109]
 [0.99467459 0.75634435 0.43259972 0.328567   0.9079651 ]]
Minumum:  0.04764385838476237
Maximum:  0.9946745879844554


5. Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.

In [8]:
array = np.random.random((10, 4))
print(array)
print('-' * 20)
first_5_rows = array[0:5, :]
print(first_5_rows)

[[0.60345137 0.78113689 0.52873114 0.80877479]
 [0.20869866 0.29800788 0.84619464 0.71954938]
 [0.13254663 0.49248024 0.74577891 0.18434602]
 [0.41382278 0.2557022  0.0955624  0.8865836 ]
 [0.9086367  0.82318134 0.14182212 0.87382846]
 [0.14497991 0.0189377  0.46798736 0.19958104]
 [0.56485186 0.22777344 0.74295219 0.19318975]
 [0.29285971 0.26884432 0.96205256 0.33152182]
 [0.82682859 0.86602283 0.19216317 0.41383577]
 [0.00566395 0.87133936 0.59700136 0.17401542]]
--------------------
[[0.60345137 0.78113689 0.52873114 0.80877479]
 [0.20869866 0.29800788 0.84619464 0.71954938]
 [0.13254663 0.49248024 0.74577891 0.18434602]
 [0.41382278 0.2557022  0.0955624  0.8865836 ]
 [0.9086367  0.82318134 0.14182212 0.87382846]]


6. Write a NumPy program to shuffle numbers between 0 and 10 (inclusive)

In [9]:
x = np.arange(10)
np.random.shuffle(x)
print(x)
print("Same result using permutation():")
print(np.random.permutation(10))

[7 5 0 9 2 6 4 8 1 3]
Same result using permutation():
[9 1 0 8 4 2 7 5 3 6]


7. Write a NumPy program to normalize a 3x3 random matrix.

In [10]:
x = np.random.random((3,3))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.49023707 0.79626227 0.13991975]
 [0.59056437 0.75732102 0.40556122]
 [0.50175851 0.92553584 0.98963049]]
After normalization:
[[0.41227833 0.77243053 0.        ]
 [0.53035062 0.72660171 0.31262577]
 [0.42583757 0.92456885 1.        ]]


8. Write a NumPy program to create a random vector of size 10 and sort it.

In [16]:
vector = np.random.random(10)
print(vector)
print('\nSorted vector')
np.sort(vector)

[0.89086001 0.1849252  0.85482807 0.48886371 0.12713774 0.48978048
 0.49207114 0.73009404 0.56281267 0.89111111]

Sorted vector


array([0.12713774, 0.1849252 , 0.48886371, 0.48978048, 0.49207114,
       0.56281267, 0.73009404, 0.85482807, 0.89086001, 0.89111111])

9. Write a NumPy program to find the nearest value from a given value in an array.

In [22]:
x = np.random.uniform(1, 12, 5)
print(x)
print('-' * 20)
v = 8
n = x.flat[np.abs(x - v).argmin()]
print(n)

[6.40131591 1.55264256 9.69931676 8.83120968 5.87572157]
--------------------
8.831209680718315
[6.40131591 1.55264256 9.69931676 8.83120968 5.87572157]


10. Write a NumPy program to check two random arrays are equal or not.

In [35]:
x = np.random.randint(1, 3, 5)
y = np.random.randint(1, 3, 5)
print(np.array_equal(x, y))
print(np.allclose(x, y))

False
False


11. Write a NumPy program to create random vector of size 15 and replace the maximum value by -1

In [38]:
x = np.random.random(size=15)
print(x)
print('-' * 20)
x[x.argmax()] = -1
print(x)

[0.07106255 0.98524987 0.44225217 0.81948785 0.27026201 0.25266551
 0.52965981 0.97962066 0.91530871 0.85176232 0.00530619 0.74594867
 0.6666663  0.51704211 0.74568273]
--------------------
[ 0.07106255 -1.          0.44225217  0.81948785  0.27026201  0.25266551
  0.52965981  0.97962066  0.91530871  0.85176232  0.00530619  0.74594867
  0.6666663   0.51704211  0.74568273]


12. Write a NumPy program to find point by point distances of a random vector with shape (10,2) representing coordinates.

In [41]:
a = np.random.randint(1, 20, (10, 2))
print(a)
print('-' * 20)
x, y = np.atleast_2d(a[:, 0], a[:, 1])
b = np.sqrt((x - x.T) ** 2 + (y - y.T) ** 2)
print(b)

[[ 2  1]
 [15 15]
 [ 8 16]
 [ 7 12]
 [ 9  2]
 [18 11]
 [ 2  5]
 [ 7  8]
 [ 3 13]
 [15 17]]
--------------------
[[ 0.         19.10497317 16.15549442 12.08304597  7.07106781 18.86796226
   4.          8.60232527 12.04159458 20.61552813]
 [19.10497317  0.          7.07106781  8.54400375 14.31782106  5.
  16.40121947 10.63014581 12.16552506  2.        ]
 [16.15549442  7.07106781  0.          4.12310563 14.03566885 11.18033989
  12.52996409  8.06225775  5.83095189  7.07106781]
 [12.08304597  8.54400375  4.12310563  0.         10.19803903 11.04536102
   8.60232527  4.          4.12310563  9.43398113]
 [ 7.07106781 14.31782106 14.03566885 10.19803903  0.         12.72792206
   7.61577311  6.32455532 12.52996409 16.15549442]
 [18.86796226  5.         11.18033989 11.04536102 12.72792206  0.
  17.08800749 11.40175425 15.13274595  6.70820393]
 [ 4.         16.40121947 12.52996409  8.60232527  7.61577311 17.08800749
   0.          5.83095189  8.06225775 17.69180601]
 [ 8.60232527 10.63014581  8.

13. Write a NumPy program to find the most frequent value in an array.

In [44]:
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[1 3 6 6 2 8 3 3 6 8 7 4 5 0 2 3 5 7 4 1 8 6 8 3 5 2 9 9 5 0 5 0 8 2 6 6 8
 6 1 7]
Most frequent value in the above array:
6


14. Write a NumPy program to convert cartesian coordinates to polar coordinates of a random 10x2 matrix representing cartesian coordinates.

In [45]:
z= np.random.random((10,2))
x,y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[0.06026628 0.28916083 0.51132356 0.56352666 0.97019793 0.50412447
 1.01424419 1.08802562 0.89988926 0.45731795]
[0.81444901 1.40040874 1.32605271 0.01976561 1.30664896 0.18556548
 0.7141461  0.83215179 0.86668751 0.77077406]


15. Write a NumPy program to find the closest value (to a given scalar) in an array.

In [46]:
x = np.arange(100)
print("Original array:")
print(x)
a = np.random.uniform(0,100)
print("Value to compare:")
print(a)
index = (np.abs(x-a)).argmin()
print(x[index])

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Value to compare:
31.645127818293307
32


16. Write a NumPy program to get the n largest values of an array.

In [52]:
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


17. Write a NumPy program to create a three-dimension array with shape (300,400,5) and set to a variable. Fill the array elements with values using unsigned integer (0 to 255)

In [98]:
nums = np.random.randint(low=0, high=256, size=(300, 400, 5), dtype=np.uint8)
print(nums)

[[[220  23 172  86 235]
  [ 47 151 212 139  25]
  [  5 173 143 191 249]
  ...
  [ 62 142  86 236 113]
  [198 111  87   5  36]
  [236  12 162 142 207]]

 [[222  35 137 216 201]
  [114  18 248 227 166]
  [117  98 171  19 211]
  ...
  [217 111 129  58 195]
  [204 177  11   0 109]
  [183 252 153 133  25]]

 [[127 140 116  40 252]
  [ 85 150 106  96 240]
  [131 248  15 179 192]
  ...
  [ 43 130 235  11  54]
  [105  45  87 121 245]
  [234  47  83   5 148]]

 ...

 [[253   5  31 175  24]
  [ 42  33 206  69  69]
  [ 60  97  46  51 232]
  ...
  [233 217 122 141 245]
  [ 61 228 230 174 157]
  [186 106 161 159 212]]

 [[159 233 246 193  89]
  [107 237  42 212 122]
  [173  94 103  59 181]
  ...
  [176 178 212 119 106]
  [109 230 139  80 182]
  [231 145 240  67 198]]

 [[154  91   8 110   5]
  [  7 112   9 106 219]
  [212  42 210 138  59]
  ...
  [ 25 116 140 168 224]
  [140 188 123 206  74]
  [ 26  11 201  19 212]]]
