1.Write a NumPy program to get the numpy version and show numpy build configuration

In [1]:
import numpy as np

print(np.__version__)
print(np.show_config())

1.24.1
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

2. Write a NumPy program to  get help on the add function

In [2]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

3. Write a NumPy program to test whether none of the elements of a given array is zero.

In [3]:
x = np.array([1, 2, 3, 4, 5])
print(np.all(x))
x = np.array([0, 1, 2, 3])
print(np.all(x))

True
False


4. Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [4]:
y = np.array([1 ,2 ,3, 0])
print(np.any(y))
y = np.zeros(1)
print(np.any(y))

True
False


5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number)

In [5]:
z = np.array([1, 0, np.nan, np.inf])
print(z)
print(np.isfinite(z))

[ 1.  0. nan inf]
[ True  True False False]


6. Write a NumPy program to test element-wise for positive or negative infinity.

In [6]:
a = np.array([-1 , 0, np.nan, -np.inf])
print(a)
print(np.isinf(a))


[ -1.   0.  nan -inf]
[False False False  True]


7. Write a NumPy program to test element-wise for NaN of a given array.

In [7]:
b = np.array([1, np.nan, np.inf])
print(b)
print(np.isnan(b))

[ 1. nan inf]
[False  True False]


8. Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.

In [8]:
c = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print(c)
print(np.iscomplex(c))
print(np.isreal(c))
print(np.isscalar([3.1]))
print(np.isscalar(3.1))

[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
[ True False False False False  True]
[False  True  True  True  True False]
False
True


9. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

In [9]:
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8], [1.0001e10,1e-9]))
print(np.allclose([1.0, np.nan], [1.0, np.nan]))
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True))

False
True
False
False
True


10. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [10]:
x = np.array([3, 5])
y = np.array([2, 5])
print(np.greater(x, y))
print(np.greater_equal(x, y))
print(np.less(x, y))
print(np.less_equal(x, y))

[ True False]
[ True  True]
[False False]
[False  True]


11. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

In [11]:
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])

print(np.equal(x, y))
print(np.allclose(x, y))

[ True  True  True  True  True  True  True  True  True False]
True


12. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [22]:
x = [1, 7, 13, 105]
y = np.array(x)
print(x)
print(y)
print("%d bytes" % (y.size * y.itemsize))

[1, 7, 13, 105]
[  1   7  13 105]
16 bytes


13. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [23]:
x = np.zeros(10)
y = np.ones(10)
z = np.ones(10) * 5
w = np.zeros(10) + 5
print(x)
print(y)
print(z)
print(w)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


14. Write a NumPy program to create an array of the integers from 30 to70.

In [27]:
np.arange(30, 71)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

15. Write a NumPy program to create an array of all the even integers from 30 to 70.

In [29]:
np.arange(30, 71, 2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

16. Write a NumPy program to create a 3x3 identity matrix.

In [30]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

17. Write a NumPy program to generate a random number between 0 and 1

In [70]:
np.random.random_sample()

0.6250863299150362

18. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [75]:
np.random.standard_normal(15)

array([ 0.00599935, -0.2060776 , -0.14199398, -0.07639362,  0.54972533,
        0.46908007,  1.06605913, -1.84176261, -0.21681916, -0.64740048,
       -0.47103796,  1.24333219,  1.93142597,  0.22173197, -0.68595402])

19. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [77]:
x = np.arange(15, 55)
print(x[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


20. Write a NumPy program to create a 3X4 array using and iterate over it

In [82]:
a = np.arange(10, 22).reshape((3, 4))
for i in np.nditer(a):
    print(i, end=" ")

10 11 12 13 14 15 16 17 18 19 20 21 