1. Write a NumPy program to print the NumPy version in your system.

In [3]:
import numpy as np

np.__version__

'1.24.1'

2. Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.

In [8]:
lst = [12.23, 13.32, 100, 36.32]
np.array(lst)

array([ 12.23,  13.32, 100.  ,  36.32])

3.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [9]:
np.arange(2, 11).reshape((3, 3))

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

4. Write a NumPy program to create a null vector of size 10 and update sixth value to 11

In [11]:
x = np.zeros(10)
x[5] = 11
x

array([ 0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.])

5. Write a NumPy program to create an array with values ranging from 12 to 38

In [13]:
np.arange(12, 38)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

6. Write a NumPy program to reverse an array (first element becomes last)

In [15]:
y = np.array([1, 2, 3, 4, 5])
y[::-1]

array([5, 4, 3, 2, 1])

7. Write a NumPy program to convert an array to a float type.

In [19]:
y = np.array([1, 2, 3, 4, 5], dtype=float)
print(y)
z = np.array([6, 7, 8, 9])
np.asfarray(z)

[1. 2. 3. 4. 5.]


array([6., 7., 8., 9.])

8. Write a NumPy program to create a 2d array with 1 on the border and 0 inside

In [47]:
a = np.ones((6, 6))
a[1:-1, 1:-1] = 0
a


array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

9. Write a NumPy program to add a border (filled with 0's) around an existing array.

In [60]:
a1 = np.arange(1, 26).reshape(5, 5)
a2 = np.pad(array=a1, pad_width=1, mode='constant', constant_values=0)
a2

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  0],
       [ 0,  6,  7,  8,  9, 10,  0],
       [ 0, 11, 12, 13, 14, 15,  0],
       [ 0, 16, 17, 18, 19, 20,  0],
       [ 0, 21, 22, 23, 24, 25,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

10. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [62]:
arr = np.ones((8, 8), dtype=int)
arr[0::2, 1::2] = 0
arr[1::2, 0::2] = 0
arr

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

11. Write a NumPy program to convert a list and tuple into arrays

In [64]:
lst = [1, 2, 3, 4, 5]
tup = ((5, 6, 7, 8, 9),(1, 1, 1, 1, 1))

print(np.array(lst))
print(np.array(tup))

[1 2 3 4 5]
[[5 6 7 8 9]
 [1 1 1 1 1]]


12. Write a NumPy program to append values to the end of an array.

In [70]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 1, 1, 1])
np.append(a, b)

array([1, 2, 3, 4, 1, 1, 1, 1])

13. Write a NumPy program to create an empty and a full array.

In [83]:
print(np.empty((3, 5)))
print(np.full((3, 4), 5))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


14. Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees and vice versa. Values are stored into a NumPy array.

In [89]:
fvalues = [0, 12, 45.21, 34, 99.91, 32]
F = np.array(fvalues)
print("Values in Fahrenheit degrees:")
print(F)
print("Values in  Centigrade degrees:")
print(np.round((5 * F / 9 - 5 * 32 / 9), 2))

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91 32.  ]
Values in  Centigrade degrees:
[-17.78 -11.11   7.34   1.11  37.73   0.  ]


In [91]:
cvalues = [-17.78, -11.11, 7.34, 1.11, 37.73, 0]
C = np.array(cvalues)
print("Values in Centigrade degrees:")
print(C)
print("Values in  Fahrenheit degrees:")
print(np.round((9  * C / 5 + 32), 2))

Values in Centigrade degrees:
[-17.78 -11.11   7.34   1.11  37.73   0.  ]
Values in  Fahrenheit degrees:
[-0.   12.   45.21 34.   99.91 32.  ]


15. Write a NumPy program to find the real and imaginary parts of an array of complex numbers.

In [96]:
a = np.array([ 1.00000000 + 0.j,  0.70710678 + 0.70710678j])
print('Real part of the array')
r = np.real(a)
print(r)
print('Imaginary part of the array')
i = np.imag(a)
print(i)

Real part of the array
[1.         0.70710678]
Imaginary part of the array
[0.         0.70710678]


In [97]:
a.real

array([1.        , 0.70710678])

In [98]:
a.imag

array([0.        , 0.70710678])

16. Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.

In [105]:
a = np.ones((3, 3))
print('The number of elements, is: ', a.size)
print('The lenght of one array element in bytes is: ', a.itemsize)
print('The total bytes consumed by the elements is: ', a.nbytes)

The number of elements, is:  9
The lenght of one array element in bytes is:  8
The total bytes consumed by the elements is:  72


17. Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

In [112]:
a = np.arange(10, dtype=float)
print(a)
b = np.ones(10)
print(b)
np.in1d(a, b)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


array([False,  True, False, False, False, False, False, False, False,
       False])

18. Write a NumPy program to find common values between two arrays.

In [115]:
arr1 = np.array([0, 10, 20, 40, 60])
arr2 = np.array([10, 30, 40])
np.intersect1d(arr1, arr2)

array([10, 40])

19. Write a NumPy program to get the unique elements of an array.

In [116]:
a = np.array([10, 10, 20, 20, 30, 30])
np.unique(a)

array([10, 20, 30])

In [117]:
a = np.array([[1, 1, 3], [3, 3, 4]])
np.unique(a)

array([1, 3, 4])

20. Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2

In [121]:
a1 = np.array([0, 10, 20, 40, 60, 80])
a2 = np.array([10, 30, 40, 50, 70, 90])
print(a1)
print(a2)
print(np.setdiff1d(a1, a2))

[ 0 10 20 40 60 80]
[10 30 40 50 70 90]
[ 0 20 60 80]
