1. Write a NumPy program to concatenate element-wise two arrays of string

In [3]:
import numpy as np

x1 = np.array(['Python', 'PHP'])
x2 = np.array([' Java', ' C++'])
print("Array1:")
print(x1)
print("Array2:")
print(x2)
new_array = np.char.add(x1, x2)
print("new array:")
print(new_array)

Array1:
['Python' 'PHP']
Array2:
[' Java' ' C++']
new array:
['Python Java' 'PHP C++']


2. Write a NumPy program to repeat all the elements three times of a given array of string

In [5]:
x1 = np.array(['Python', 'PHP', 'Java', 'C++'])
print("Original Array:")
print(x1)
new_array = np.char.multiply(x1, 3)
print("New array:")
print(new_array)

Original Array:
['Python' 'PHP' 'Java' 'C++']
New array:
['PythonPythonPython' 'PHPPHPPHP' 'JavaJavaJava' 'C++C++C++']


3. Write a NumPy program to capitalize the first letter, lowercase, uppercase, swapcase, title-case of all the elements of a given array.

In [6]:
x = np.array(['python', 'PHP', 'java', 'C++'])
print("Original Array:")
print(x)
capitalized_case = np.char.capitalize(x)
lowered_case = np.char.lower(x)
uppered_case = np.char.upper(x)
swapcased_case = np.char.swapcase(x)
titlecased_case = np.char.title(x)
print("\nCapitalized: ", capitalized_case)
print("Lowered: ", lowered_case)
print("Uppered: ", uppered_case)
print("Swapcased: ", swapcased_case)
print("Titlecased: ", titlecased_case)

Original Array:
['python' 'PHP' 'java' 'C++']

Capitalized:  ['Python' 'Php' 'Java' 'C++']
Lowered:  ['python' 'php' 'java' 'c++']
Uppered:  ['PYTHON' 'PHP' 'JAVA' 'C++']
Swapcased:  ['PYTHON' 'php' 'JAVA' 'c++']
Titlecased:  ['Python' 'Php' 'Java' 'C++']


4. Write a NumPy program to make the length of each element 15 of a given array and the string centered / left-justified / right-justified with paddings of _.

In [8]:
x = np.array(['python exercises', 'PHP', 'java', 'C++'])
print("Original Array:")
print(x)
centered = np.char.center(x, 15, fillchar='_')
left = np.char.ljust(x, 15, fillchar='_')
right = np.char.rjust(x, 15, fillchar='_')
print("\nCentered =", centered)
print("Left =", left)
print("Right =", right)

Original Array:
['python exercises' 'PHP' 'java' 'C++']

Centered = ['python exercise' '______PHP______' '______java_____' '______C++______']
Left = ['python exercise' 'PHP____________' 'java___________' 'C++____________']
Right = ['python exercise' '____________PHP' '___________java' '____________C++']


5. Write a NumPy program to insert a space between characters of all the elements of a given array.

In [10]:
x = np.array(['python exercises', 'PHP', 'java', 'C++'])
print("Original Array:")
print(x)
r = np.char.join(" ", x)
print(r)

Original Array:
['python exercises' 'PHP' 'java' 'C++']
['p y t h o n   e x e r c i s e s' 'P H P' 'j a v a' 'C + +']


6. Write a NumPy program to encode all the elements of a given array in cp500 and decode it again

In [11]:
x = np.array(['python exercises', 'PHP', 'java', 'C++'])
print("Original Array:")
print(x)
encoded_char = np.char.encode(x, 'cp500')
decoded_char = np.char.decode(encoded_char,'cp500')
print("\nencoded =", encoded_char)
print("decoded =", decoded_char)

Original Array:
['python exercises' 'PHP' 'java' 'C++']

encoded = [b'\x97\xa8\xa3\x88\x96\x95@\x85\xa7\x85\x99\x83\x89\xa2\x85\xa2'
 b'\xd7\xc8\xd7' b'\x91\x81\xa5\x81' b'\xc3NN']
decoded = ['python exercises' 'PHP' 'java' 'C++']


7. Write a NumPy program to remove the leading and trailing whitespaces of all the elements of a given array.

In [12]:
x = np.array([' python exercises ', ' PHP  ', ' java  ', '  C++'])
print("Original Array:")
print(x)
stripped = np.char.strip(x)
print("\nRemove the leading and trailing whitespaces: ", stripped)

Original Array:
[' python exercises ' ' PHP  ' ' java  ' '  C++']

Remove the leading and trailing whitespaces:  ['python exercises' 'PHP' 'java' 'C++']


8. Write a NumPy program to remove the leading whitespaces of all the elements of a given array.

In [14]:
x = np.array([' python exercises ', ' PHP  ', ' java  ', '  C++'])
print("Original Array:")
print(x)
lstripped_char = np.char.lstrip(x)
print("\nRemove the leading whitespaces : ", lstripped_char)

Original Array:
[' python exercises ' ' PHP  ' ' java  ' '  C++']

Remove the leading whitespaces :  ['python exercises ' 'PHP  ' 'java  ' 'C++']


9. Write a NumPy program to remove the trailing whitespaces of all the elements of a given array.

In [16]:
x = np.array([' python exercises ', ' PHP  ', ' java  ', '  C++'])
print("Original Array:")
print(x)
rstripped_char = np.char.rstrip(x)
print("\nRemove the trailing whitespaces : ", rstripped_char)

Original Array:
[' python exercises ' ' PHP  ' ' java  ' '  C++']

Remove the trailing whitespaces :  [' python exercises' ' PHP' ' java' '  C++']


10. Write a NumPy program to split the element of a given array with spaces. 

In [17]:
x = np.array(['Python PHP Java C++'])
print("Original Array:")
print(x)
r = np.char.split(x)
print("\nSplit the element of the said array with spaces: ")
print(r)

Original Array:
['Python PHP Java C++']

Split the element of the said array with spaces: 
[list(['Python', 'PHP', 'Java', 'C++'])]


11. Write a NumPy program to split the element of a given array to multiple lines.

In [18]:
x = np.array(['Python\Exercises, Practice, Solution'])
print("Original Array:")
print(x)
r = np.char.splitlines(x)
print(r)

Original Array:
['Python\\Exercises, Practice, Solution']
[list(['Python\\Exercises, Practice, Solution'])]


12. Write a NumPy program to make all the elements of a given string to a numeric string of 5 digits with zeros on its left.

In [19]:
x = np.array(['2', '11', '234', '1234', '12345'])
print("\nOriginal Array:")
print(x)
r = np.char.zfill(x, 5)
print("\nNumeric string of 5 digits with zeros:")
print(r) 


Original Array:
['2' '11' '234' '1234' '12345']

Numeric string of 5 digits with zeros:
['00002' '00011' '00234' '01234' '12345']


13. Write a NumPy program to replace "PHP" with "Python" in the element of a given array.

In [21]:
x = np.array(['PHP Exercises, Practice, Solution'])
print("\nOriginal Array:")
print(x)
r = np.char.replace(x, "PHP", "Python")
print("\nNew array:")
print(r)


Original Array:
['PHP Exercises, Practice, Solution']

New array:
['Python Exercises, Practice, Solution']


14. Write a NumPy program to test equal, not equal, greater equal, greater and less test of all the elements of two given arrays.

In [22]:
x1 = np.array(['Hello', 'PHP', 'JS', 'examples', 'html'])
x2 = np.array(['Hello', 'php', 'Java', 'examples', 'html'])
print("\nArray1:")
print(x1)
print("Array2:")
print(x2)
print("\nEqual test:")
r = np.char.equal(x1, x2)
print(r)
print("\nNot equal test:")
r = np.char.not_equal(x1, x2)
print(r)
print("\nLess equal test:")
r = np.char.less_equal(x1, x2)
print(r)
print("\nGreater equal test:")
r = np.char.greater_equal(x1, x2)
print(r)
print("\nLess test:")
r = np.char.less(x1, x2)
print(r)


Array1:
['Hello' 'PHP' 'JS' 'examples' 'html']
Array2:
['Hello' 'php' 'Java' 'examples' 'html']

Equal test:
[ True False False  True  True]

Not equal test:
[False  True  True False False]

Less equal test:
[ True  True  True  True  True]

Greater equal test:
[ True False False  True  True]

Less test:
[False  True  True False False]


15. Write a NumPy program to count the number of "P" in a given array, element-wise.

In [24]:
x1 = np.array(['Python', 'PHP', 'JS', 'examples', 'html'])
print("\nOriginal Array:")
print(x1)
print("Number of \'P\':")
r = np.char.count(x1, "P")
print(r)


Original Array:
['Python' 'PHP' 'JS' 'examples' 'html']
Number of 'P':
[1 2 0 0 0]


16. Write a NumPy program to count the lowest index of "P" in a given array, element-wise

In [26]:
x1 = np.array(['Python', 'PHP', 'JS', 'EXAMPLES', 'HTML'])
print("\nOriginal Array:")
print(x1)
print("count the lowest index of \'P\':")
r = np.char.find(x1, "P")
print(r)


Original Array:
['Python' 'PHP' 'JS' 'EXAMPLES' 'HTML']
count the lowest index of 'P':
[ 0  0 -1  4 -1]


17. Write a NumPy program to check whether each element of a given array is composed of digits only, lower case letters only and upper case letters only

In [28]:
x = np.array(['Python', 'PHP', 'JS', 'Examples', 'html5', '5'])
print("\nOriginal Array:")
print(x)
r1 = np.char.isdigit(x)
r2 = np.char.islower(x)
r3 = np.char.isupper(x)
print("Digits only =", r1)
print("Lower cases only =", r2)
print("Upper cases only =", r3)


Original Array:
['Python' 'PHP' 'JS' 'Examples' 'html5' '5']
Digits only = [False False False False False  True]
Lower cases only = [False False False False  True False]
Upper cases only = [False  True  True False False False]


18. Write a NumPy program to check whether each element of a given array starts with "P"

In [30]:
x1 = np.array(['Python', 'PHP', 'JS', 'examples', 'html'])
print("\nOriginal Array:")
print(x1)
print("Test if each element of the said array starts with 'P':")
r = np.char.startswith(x1, "P")
print(r)


Original Array:
['Python' 'PHP' 'JS' 'examples' 'html']
Test if each element of the said array starts with 'P':
[ True  True False False False]


19. Write a NumPy program to add two zeros to the beginning of each element of a given array of string values.

In [31]:
nums = np.array(['1.12', '2.23', '3.71', '4.23', '5.11'])
print("Original array:")
print(nums)
print("\nAdd two zeros to the beginning of each element of the said array:")
print(np.char.add('00', nums))
print("\nAlternate method:")
print(np.char.rjust(nums, 6, fillchar='0'))

Original array:
['1.12' '2.23' '3.71' '4.23' '5.11']

Add two zeros to the beginning of each element of the said array:
['001.12' '002.23' '003.71' '004.23' '005.11']

Alternate method:
['001.12' '002.23' '003.71' '004.23' '005.11']


20. Write a NumPy program to replace a specific character with another in a given array of string values.

In [32]:
str1 = np.array([['Python-NumPy-Exercises'],
              ['-Python-']])
print("Original array of string values:") 
print(str1)
print("\nReplace '-' with '=' character in the said array of string values:")
print(np.char.strip(np.char.replace(str1, '-', '==')))
print("\nReplace '-' with ' ' character in the said array of string values:")
print(np.char.strip(np.char.replace(str1, '-', ' ')))

Original array of string values:
[['Python-NumPy-Exercises']
 ['-Python-']]

Replace '-' with '=' character in the said array of string values:
[['Python==NumPy==Exercises']
 ['==Python==']]

Replace '-' with ' ' character in the said array of string values:
[['Python NumPy Exercises']
 ['Python']]


21. Write a NumPy program to count a given word in each row of a given array of string values.

In [33]:
str1 = np.array([['Python','NumPy','Exercises'],
                 ['Python','Pandas','Exercises'],
                 ['Python','Machine learning','Python']])
print("Original array of string values:") 
print(str1)
print("\nCount 'Python' row wise in the above array of string values:")
print(np.char.count(str1, 'Python'))

Original array of string values:
[['Python' 'NumPy' 'Exercises']
 ['Python' 'Pandas' 'Exercises']
 ['Python' 'Machine learning' 'Python']]

Count 'Python' row wise in the above array of string values:
[[1 0 0]
 [1 0 0]
 [1 0 1]]


22. Write a NumPy program to split a given text into lines and split the single line into array values.

In [34]:
student = """01	V	Debby Pramod
02	V	Artemiy Ellie
03	V	Baptist Kamal
04	V	Lavanya Davide
05	V	Fulton Antwan
06	V	Euanthe Sandeep
07	V	Endzela Sanda
08	V	Victoire Waman
09	V	Briar Nur
10	V	Rose Lykos"""

print("Original text:") 
print(student)
text_lines = student.splitlines()
text_lines = [r.split('\t') for r in text_lines]
result = np.array(text_lines)
print("\nArray from the said text:")
print(result)

Original text:
01	V	Debby Pramod
02	V	Artemiy Ellie
03	V	Baptist Kamal
04	V	Lavanya Davide
05	V	Fulton Antwan
06	V	Euanthe Sandeep
07	V	Endzela Sanda
08	V	Victoire Waman
09	V	Briar Nur
10	V	Rose Lykos

Array from the said text:
[['01' 'V' 'Debby Pramod']
 ['02' 'V' 'Artemiy Ellie']
 ['03' 'V' 'Baptist Kamal']
 ['04' 'V' 'Lavanya Davide']
 ['05' 'V' 'Fulton Antwan']
 ['06' 'V' 'Euanthe Sandeep']
 ['07' 'V' 'Endzela Sanda']
 ['08' 'V' 'Victoire Waman']
 ['09' 'V' 'Briar Nur']
 ['10' 'V' 'Rose Lykos']]
